spring.application.name=snippet
# El puerto se obtiene de la variable de entorno SERVER_PORT
server.port=${SERVER_PORT}

# --- Configuración de la Base de Datos ---
# Se obtienen de las variables de entorno de Docker Compose
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Configuración de Seguridad (Resource Server) ---
# Valida los tokens JWT usando las variables de entorno
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH0_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.audiences=${AUTH0_AUDIENCE}

# --- URLs de servicios ---
# URL para el cliente RestTemplate que llamará al auth-service
service.auth.url=${AUTH_SERVICE_URL}